### ISSUE TITLE
Cannot do more than one iteration; nothing in iterations.txt file

### ISSUE THREAD

**Issue by bjkramerumnedu** [lmlui/Jorg#12]
Hello,

I have a bin with 43 contigs. The metabat2 merged.depth.txt output shows that average value of the totalAvgDepth is ~17.1.

I have used that value for -c (coverage), as well as the highest coverage value among the contigs (156.4), as well as the minimum coverage of 75% of the top contig, which I interpreted as ~118. I've gotten the same results: nothing in the iterations.txt file, and only one iteration instead of the requested 5, as well as no change in the number of contigs in the output .fasta file.

This is the code I've run:

/home/sheikc/bjkramer/Jorg/jorg -b bin.007.fastaDlemm_DasTool_assembly.fa -r D_lemm.fastq -k 33 -c 12 -i 5 --high_contig_num no 

Since the average coverage is ~17, is it possible to successfully run Jorg on this bin? Would it be possible to do anything to resolve this issue so I can run Jorg.

Any help would be greatly appreciated. Thank you.

**Comment by lmlui** [comment]
Can you post the output of log file?

**Comment by bjkramerumnedu** [comment]
Thank you! There were two .log files: mira_iteration_1.log and mirabait_iteration_1.log. Please see attached.

[mira_iteration_1.log](https://github.com/lmlui/Jorg/files/12455272/mira_iteration_1.log)

[mirabait_iteration_1 (2).log](https://github.com/lmlui/Jorg/files/12455274/mirabait_iteration_1.2.log)

**Comment by tnn111** [comment]
Hi,

If you look at the log file, there’s this section:

1) RECOMMENDED! Use -DI:trt to redirect the tmp directory somewhere else on a
   local disk or even SSD.
2) ALSO POSSIBLE: put the whole project somewhere else on your file system.
3) ABSOLUTELY NOT RECOMMENDED AT ALL: use "-NW:cnfs=warn" to tell MIRA not
   to stop when it finds the tmp directory on NFS.

I think the problem is that you are on a network file system and that’s a problem for MIRA because of the heavy reliance on temporary files. I’m opt for either 1) or 2). Either way, you need to be somewhere the file system isn’t network mounted. Your systems people should be able to tell you where to redirect to if you choose 1). Quite possibly, /tmp will work…… You should probably edit and add the option line to the MIRA configuration file.

If you are on a cluster with really high performance file systems, you could do 3), but for that, you’d still have to edit the MIRA configuration file.

Good luck, Torben
